### ISSUE TITLE
Working twitter streaming API in python

### ISSUE THREAD

**Issue by owlas** [owlas/twaca#1]
Need to use an existing wrapper for the twitter streaming API in python. Get this working and start parsing the tweet data.

**Comment by owlas** [comment]
Here is the wrapper http://geduldig.github.io/TwitterAPI/

**Comment by owlas** [comment]
How to process output data JSON file https://dev.twitter.com/streaming/overview/processing

**Comment by owlas** [comment]
Got a live stream going, need to write a script to just run this from the command line

**Comment by owlas** [comment]
It's done!

**Comment by mit-24** [comment]
https://cloud.google.com/sdk/
installing SDK
